name: Unit Testing

on:
  push:
    branches:
    - develop
    
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit testing
    steps:
    - uses: actions/checkout@v3
    - name: unit testing
      run: cd tests && make tests
