name: Unit Testing

on:
  pull_request:
    branches:
    - develop
    - main

jobs:
  build:
    runs-on: macos-latest
    name: Unit Testing
    steps:
    - uses: actions/checkout@v3
    - name: Build Minishell
      run: make
    - name: Unit Testing
      run: make tests
